name: 'Setup OSSUTIL environment'
description: 'Download and config Alibaba Cloud OSSUTIL'
author: 'Rimo'
inputs:
  ossutil-version:
    description: 'The OSSUTIL version to download and use'
    required: false
    default: '1.7.14'
  endpoint:
    description: 'The endpoint of your bucket'
    required: true
  access-key-id:
    description: 'The AccessKeyID of the credentials'
    required: true
  access-key-secret:
    description: 'The AccessKeySecret of the credentials'
    required: true
  sts-token:
    description: 'The STS Token of the credentials'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'download-cloud'
  color: 'orange'
