name: 'Setup OSSUTIL environment'
description: 'Download and config Alibaba Cloud OSSUTIL'
author: 'Rimo'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'download-cloud'
  color: 'orange'

# Define your inputs here.
inputs:
  ossutil-version:
    description: 'The OSSUTIL version to download and use, or "latest" for the latest version.'
    required: true
    default: '1.7.14'
  endpoint:
    description: 'The endpoint of your bucket'
    required: false
  access-key-id:
    description: 'The AccessKey ID of the credentials'
    required: false
  access-key-secret:
    description: 'The AccessKey Secret of the credentials'
    required: false
  sts-token:
    description: 'The STS Token of the credentials'
    required: false

# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
