name: "functional"
on:
  schedule:
    - cron: '0 2 * * 6'

jobs:
  functional:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [1.7.0, 1.7.14, latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: yizhoumo/setup-ossutil@v1
      with:
        ossutil-version: ${{ matrix.version }}
        endpoint: ${{ secrets.OSS_ENDPOINT }}
        access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
    - run: ossutil -v
    - run: ossutil ls > /dev/null
      shell: bash
